version: "3.9"

services:
  backend:
    container_name: flask_api
    build:
      context: .
      dockerfile: flask_api.dockerfile
    ports:
      - "5001:5001"
    env_file:
      - .env
    command: >
      gunicorn -k eventlet -w 4
      -b 0.0.0.0:5001
      mtaa_backend:app
    restart: unless-stopped
    networks:
      - MTAA_network

networks:
  MTAA_network:
    external: true