services:
  web:
    container_name: flask_api
    build:
      context: .
      dockerfile: flask_api.dockerfile
    ports:
      - "5001:5001"
    env_file:
      - .env
    networks:
      - MTAA_network

networks:
  MTAA_network:
    external: true